// Read-only deployed HTTP checks. No personal data or form submission.
const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const base=process.env.VISPO_BASE||'https://vispo-website.pages.dev';const mode=process.env.VISPO_MODE||'preview';const browser=await chromium.launch();const p=await browser.newPage({viewport:{width:390,height:900}});await p.goto(base+'/');const redirects=fs.readFileSync('_redirects','utf8').split('\n').filter(l=>l.trim()&&!l.startsWith('#')).map(l=>{let [from,to,status]=l.trim().split(/\s+/);return {from,to,status:Number(status)}});let errors=[];
const checked=[];let next=0;
async function checkWorker(){while(next<redirects.length){const rule=redirects[next++];try{const r=await p.context().request.head(base+rule.from,{maxRedirects:0,timeout:12000});checked.push({from:rule.from,expected:rule.to,actual:r.headers().location,status:r.status()});}catch(e){checked.push({from:rule.from,error:e.message})}if(checked.length%100===0)console.log('Redirect HEAD checks: '+checked.length)}}
await Promise.all([checkWorker(),checkWorker(),checkWorker(),checkWorker(),checkWorker(),checkWorker()]);
for(const r of checked)if(r.error||r.status!==301||r.actual!==r.expected)errors.push(r);
for(const file of ['/docs/production-cutover.txt','/site-config.json','/scripts/build.py','/tests/forms.cjs','/README.md','/this-page-does-not-exist','/sample-page']){const r=await p.goto(base+file,{waitUntil:'domcontentloaded',timeout:15000});if(r.status()!==404)errors.push({path:file,status:r.status(),expected:404})}
for(const path of ['/','/web','/trial','/inquiry','/schedule','/archive-4342','/receipt']){const r=await p.goto(base+path,{waitUntil:'domcontentloaded',timeout:15000});if(r.status()!==200)errors.push({path,status:r.status()});if(mode==='preview'&&!String(r.headers()['x-robots-tag']).includes('noindex'))errors.push({path,error:'missing noindex header'});const canonical=await p.locator('link[rel="canonical"]').getAttribute('href');if(canonical!=='https://vispo-fit.com'+(path==='/'?'/':path))errors.push({path,error:'canonical'});if(await p.locator('[href^="https://vispo-fit.com"]:not([rel="canonical"]),[src^="https://vispo-fit.com"]').count())errors.push({path,error:'old-site dependency'});}
let chainChecks=[];for(const path of ['/policy/','/vispo24','/archives/4342.html','/web_thanks']){let r=await p.goto(base+path,{waitUntil:'domcontentloaded',timeout:15000});let req=r.request();let statuses=[];while(req.redirectedFrom()){req=req.redirectedFrom();statuses.push((await req.response()).status())}chainChecks.push({path,statuses,final:p.url()});if(!statuses.includes(301))errors.push({path,error:'no 301 in redirect chain'})}
await p.goto(base+'/');await p.screenshot({path:'reports/public-home.png',fullPage:true});await browser.close();fs.writeFileSync('reports/release-checks.json',JSON.stringify({mode,redirects:checked.length,chainChecks,errors},null,2));console.log(JSON.stringify({redirects:checked.length,chainChecks,errors}));process.exitCode=errors.length?1:0})().catch(e=>{console.error(e);process.exit(1)});
